name: Create Release

on: [workflow_dispatch]

# Since we are reusing a workflow, we must match the permissions that
# upstream workflow requires.
permissions:
  contents: write
  id-token: write

jobs:
  tag-and-publish:
    uses: newrelic/node-newrelic/.github/workflows/release-creation.yml@main
    with:
      changelog_file: CHANGELOG.md
